### ISSUE TITLE
Add completion to Homebrew/homebrew-core?

### ISSUE THREAD

**Issue by tonglil** [iljaweis/vault-bash-completion#11]
Any chance you are planning to add this to https://github.com/Homebrew/homebrew-core and make it installable by homebrew? I'd hate to lose this when I switch computers.

**Comment by iljaweis** [comment]
To be honest, that feels like it would lead to a lot more support/maintenance than I'm able to manage...

**Comment by iljaweis** [comment]
Closing this because vault now has built-in autocompletion support.
